// ─────────────────────────────────────────────────────────
// presets.js — Built-in module library for WFC dungeon generation
//
// All modules are 8×8 tiles. Edge patterns determine socket compatibility.
//
// Socket types (8-char patterns derived from edge tiles):
//   Wall:     WWWWWWWW  (solid wall — no connection)
//   Standard: WWOOOOWW  (centered 4-wide opening — corridors & room entrances)
//   Narrow:   WWWOOWWW  (centered 2-wide opening — tight passages & side doors)
//   Interior: WOOOOOOW  (6-wide opening — grand multi-module room joins)
//
// Tile types: W=wall, F=floor, D=door, C=corridor, S=spawn, X=chest, E=enemy, B=boss
//
// Content decoration fields:
//   contentRole: 'flexible' | 'fixed' | 'structural'
//   spawnSlots: [{ x, y, types: ['enemy','loot','spawn','boss'] }]
//   maxEnemies / maxChests: caps for decorator placement
//   canBeBoss / canBeSpawn: eligibility flags
// ─────────────────────────────────────────────────────────

export const PRESET_MODULES = [
  // ═══════════════════════════════════════════════════════
  // FILLER
  // ═══════════════════════════════════════════════════════
  {
    id: 'preset_solid',
    name: 'Solid Wall',
    purpose: 'empty',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 3.0,
    allowRotation: false,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  // ═══════════════════════════════════════════════════════
  // CORRIDORS — standard 4-wide (socket WWOOOOWW)
  // ═══════════════════════════════════════════════════════
  {
    id: 'preset_corridor_h',
    name: 'Corridor Straight',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 2.0,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  {
    id: 'preset_corridor_l',
    name: 'Corridor L-Turn',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 1.5,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','F','W','W'],
      ['F','F','F','F','F','F','W','W'],
      ['F','F','F','F','F','F','W','W'],
      ['F','F','F','F','F','F','W','W'],
      ['W','W','F','F','F','F','W','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  {
    id: 'preset_corridor_t',
    name: 'Corridor T-Junction',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 1.0,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','F','F','F','F','W','W'],
      ['W','W','F','F','F','F','W','W'],
      ['W','W','F','F','F','F','F','F'],
      ['W','W','F','F','F','F','F','F'],
      ['W','W','F','F','F','F','F','F'],
      ['W','W','F','F','F','F','F','F'],
      ['W','W','F','F','F','F','W','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  {
    id: 'preset_corridor_cross',
    name: 'Corridor Crossroads',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.5,
    allowRotation: false,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','F','F','F','F','W','W'],
      ['W','W','F','F','F','F','W','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','W','F','F','F','F','W','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  // ═══════════════════════════════════════════════════════
  // ROOMS — generic rooms with various exit configs
  // All are 'flexible' — the decorator can assign content
  // Interior floor area: 6×6 = 36 tiles (positions 1-6)
  // ═══════════════════════════════════════════════════════
  {
    id: 'preset_room_dead_end',
    name: 'Dead End Room',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 1.0,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn', 'boss'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 2, types: ['enemy', 'loot', 'boss'] },
      { x: 4, y: 2, types: ['enemy', 'loot'] },
      { x: 1, y: 4, types: ['enemy', 'loot'] },
      { x: 6, y: 4, types: ['enemy', 'loot'] },
      { x: 2, y: 5, types: ['enemy', 'loot'] },
      { x: 5, y: 5, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 5,
    maxChests: 3,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  {
    id: 'preset_room_straight',
    name: 'Room Passthrough',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 1.2,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 2, types: ['enemy', 'loot'] },
      { x: 4, y: 2, types: ['enemy', 'loot'] },
      { x: 1, y: 5, types: ['enemy', 'loot'] },
      { x: 6, y: 5, types: ['enemy', 'loot'] },
      { x: 3, y: 6, types: ['enemy', 'loot', 'boss'] },
      { x: 4, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 5,
    maxChests: 3,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','F','F','F','F','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  {
    id: 'preset_room_corner',
    name: 'Room Corner',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 1.0,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn', 'boss'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 5, y: 3, types: ['enemy', 'loot'] },
      { x: 1, y: 5, types: ['enemy', 'loot'] },
      { x: 6, y: 5, types: ['enemy', 'loot'] },
      { x: 2, y: 6, types: ['enemy', 'loot'] },
      { x: 5, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 5,
    maxChests: 3,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  {
    id: 'preset_room_three',
    name: 'Room Three-Way',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.8,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 5, y: 3, types: ['enemy', 'loot'] },
      { x: 1, y: 5, types: ['enemy', 'loot'] },
      { x: 6, y: 5, types: ['enemy', 'loot'] },
      { x: 2, y: 6, types: ['enemy', 'loot', 'boss'] },
      { x: 5, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 5,
    maxChests: 3,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  {
    id: 'preset_room_hub',
    name: 'Room Hub',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.4,
    allowRotation: false,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 4, y: 4, types: ['enemy', 'loot', 'boss'] },
      { x: 1, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
      { x: 2, y: 2, types: ['enemy', 'loot'] },
      { x: 5, y: 5, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 5,
    maxChests: 3,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','F','F','F','F','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  // ═══════════════════════════════════════════════════════
  // SPECIAL PURPOSE ROOMS — 'fixed' content baked into tiles
  // ═══════════════════════════════════════════════════════
  {
    id: 'preset_spawn_room',
    name: 'Spawn Room',
    purpose: 'spawn',
    contentRole: 'fixed',
    width: 8,
    height: 8,
    weight: 0.3,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','S','S','S','S','S','S','W'],
      ['W','S','S','S','S','S','S','W'],
      ['W','S','S','F','F','S','S','W'],
      ['W','S','F','F','F','F','S','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  {
    id: 'preset_enemy_room',
    name: 'Enemy Den',
    purpose: 'enemy',
    contentRole: 'fixed',
    width: 8,
    height: 8,
    weight: 1.5,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','E','F','F','F','W'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','E','F','F','F','E','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','E','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  {
    id: 'preset_enemy_room_2',
    name: 'Skeleton Hall',
    purpose: 'enemy',
    contentRole: 'fixed',
    width: 8,
    height: 8,
    weight: 1.2,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','F','F','F','F','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','E','F','F','E','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','E','F','F','E','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  {
    id: 'preset_loot_room',
    name: 'Treasury',
    purpose: 'loot',
    contentRole: 'fixed',
    width: 8,
    height: 8,
    weight: 0.5,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','X','F','F','X','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['W','F','X','F','F','X','F','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  {
    id: 'preset_boss_room',
    name: 'Boss Chamber',
    purpose: 'boss',
    contentRole: 'fixed',
    width: 8,
    height: 8,
    weight: 0.2,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','B','B','F','F','W'],
      ['W','F','F','B','B','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },

  // ═══════════════════════════════════════════════════════
  // CORRIDOR WITH DOOR VARIANTS
  // ═══════════════════════════════════════════════════════
  {
    id: 'preset_door_corridor_h',
    name: 'Doored Corridor',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.8,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','C','C','F','F','F'],
      ['F','F','F','C','C','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  // ═══════════════════════════════════════════════════════
  // MULTI-MODULE ROOMS — Grand / Large Room Pieces
  //
  // These modules use a special "interior join" socket (WOOOOOOW)
  // on edges that connect to other room segments. The WFC
  // constraint propagation forces matching segments together,
  // creating rooms that span 2, 4, or 9+ modules.
  //
  // Interior join socket: WOOOOOOW (6-wide opening — walls at corners)
  // Standard corridor:    WWOOOOWW (centered 4-wide opening)
  // Solid wall:           WWWWWWWW (no connection)
  // ═══════════════════════════════════════════════════════

  // ─── 2-Module Room Pieces ──────────────────────────────

  {
    id: 'preset_grand_hall',
    name: 'Grand Hall',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.5,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 5, y: 4, types: ['enemy', 'loot'] },
      { x: 1, y: 5, types: ['enemy', 'loot'] },
      { x: 4, y: 6, types: ['enemy', 'loot', 'boss'] },
      { x: 2, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 5,
    maxChests: 3,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  {
    id: 'preset_grand_hall_pillared',
    name: 'Grand Hall Pillared',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.4,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot'] },
      { x: 3, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 5, y: 4, types: ['enemy', 'loot'] },
      { x: 1, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','W','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','W','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  {
    id: 'preset_grand_end',
    name: 'Grand End',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.4,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn', 'boss'] },
      { x: 5, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 2, y: 3, types: ['enemy', 'loot'] },
      { x: 5, y: 3, types: ['enemy', 'loot'] },
      { x: 1, y: 5, types: ['enemy', 'loot', 'boss'] },
      { x: 5, y: 5, types: ['enemy', 'loot'] },
      { x: 3, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 5,
    maxChests: 3,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  // ─── 4-Module Room Corners (2×2 Grand Rooms) ──────────

  {
    id: 'preset_grand_corner_closed',
    name: 'Grand Corner Closed',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.3,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn', 'boss'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 3, types: ['enemy', 'loot'] },
      { x: 5, y: 5, types: ['enemy', 'loot', 'boss'] },
      { x: 1, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 5,
    maxChests: 3,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
    ],
  },

  {
    id: 'preset_grand_corner_open',
    name: 'Grand Corner Open',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.4,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 5, y: 5, types: ['enemy', 'loot'] },
      { x: 1, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 5,
    maxChests: 3,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
    ],
  },

  {
    id: 'preset_grand_corner_double',
    name: 'Grand Corner Double',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.3,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot'] },
      { x: 3, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 5, y: 5, types: ['enemy', 'loot'] },
      { x: 1, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 5,
    maxChests: 3,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','F','F','F','F','W','W'],
      ['W','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
    ],
  },

  {
    id: 'preset_grand_corner_pillared',
    name: 'Grand Corner Pillared',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.35,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot'] },
      { x: 5, y: 3, types: ['enemy', 'loot'] },
      { x: 1, y: 5, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot', 'boss'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','W','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
    ],
  },

  // ─── Special Purpose Grand Rooms — 'fixed' content ────

  {
    id: 'preset_grand_enemy_den',
    name: 'Grand Enemy Den',
    purpose: 'enemy',
    contentRole: 'fixed',
    width: 8,
    height: 8,
    weight: 0.4,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','E','F','F','F','F','E','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','E','F','F','F','F','F'],
      ['F','F','F','F','F','E','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','E','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  {
    id: 'preset_grand_boss_arena',
    name: 'Grand Boss Arena',
    purpose: 'boss',
    contentRole: 'fixed',
    width: 8,
    height: 8,
    weight: 0.1,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','B','B','F','F','F'],
      ['W','F','F','B','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
    ],
  },

  {
    id: 'preset_grand_treasury',
    name: 'Grand Treasury',
    purpose: 'loot',
    contentRole: 'fixed',
    width: 8,
    height: 8,
    weight: 0.2,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','X','F','F','X','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','X','F','F','X','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  {
    id: 'preset_grand_spawn',
    name: 'Grand Spawn Hall',
    purpose: 'spawn',
    contentRole: 'fixed',
    width: 8,
    height: 8,
    weight: 0.15,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','S','S','S','S','S','S','F'],
      ['F','S','S','S','S','S','S','F'],
      ['F','S','S','F','F','S','S','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  // ─── 3×3+ Room Interior Pieces — structural ───────────

  {
    id: 'preset_grand_center',
    name: 'Grand Center',
    purpose: 'empty',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.2,
    allowRotation: false,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
    ],
  },

  {
    id: 'preset_grand_edge',
    name: 'Grand Edge',
    purpose: 'empty',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.25,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
    ],
  },

  // ═══════════════════════════════════════════════════════
  // NARROW CORRIDORS — 2-wide passages (socket: WWWOOWWW)
  // Creates tight squeeze corridors, ambush chokepoints,
  // and secret passages. Diablo 2-style variety.
  // ═══════════════════════════════════════════════════════
  {
    id: 'preset_narrow_corridor_h',
    name: 'Narrow Corridor Straight',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 1.2,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },
  {
    id: 'preset_narrow_corridor_l',
    name: 'Narrow Corridor L-Turn',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.9,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','W','W','W'],
      ['F','F','F','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
    ],
  },
  {
    id: 'preset_narrow_corridor_t',
    name: 'Narrow Corridor T-Junction',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.6,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','F','F','F'],
      ['W','W','W','F','F','F','F','F'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
    ],
  },
  {
    id: 'preset_narrow_crossroads',
    name: 'Narrow Crossroads',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.3,
    allowRotation: false,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
    ],
  },
  {
    id: 'preset_narrow_door_corridor',
    name: 'Narrow Doored Corridor',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.5,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','C','C','F','F','F'],
      ['F','F','F','C','C','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  // ═══════════════════════════════════════════════════════
  // TRANSITION MODULES — bridge different socket widths
  // Narrow↔Standard and Standard↔Wide (Grand) connectors.
  // ═══════════════════════════════════════════════════════
  {
    id: 'preset_narrow_to_standard',
    name: 'Narrow-to-Standard Widener',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 1.0,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','W','W','F','F','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },
  {
    id: 'preset_standard_to_wide',
    name: 'Standard-to-Wide Vestibule',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.6,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','W','F','F','F','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  // ═══════════════════════════════════════════════════════
  // ASYMMETRIC / MIXED-SOCKET ROOMS
  // Rooms with different socket types per edge, creating
  // varied spatial rhythm (main entrance vs side passage).
  // ═══════════════════════════════════════════════════════
  {
    id: 'preset_room_alcove',
    name: 'Alcove Room',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.8,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn', 'boss'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 3, types: ['enemy', 'loot'] },
      { x: 5, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 1, y: 5, types: ['enemy', 'loot'] },
      { x: 6, y: 5, types: ['enemy', 'loot'] },
      { x: 3, y: 6, types: ['enemy', 'loot'] },
      { x: 5, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },
  {
    id: 'preset_room_side_passage',
    name: 'Side Passage Room',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.7,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot'] },
      { x: 3, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 5, y: 3, types: ['enemy', 'loot'] },
      { x: 1, y: 5, types: ['enemy', 'loot'] },
      { x: 6, y: 5, types: ['enemy', 'loot'] },
      { x: 3, y: 6, types: ['enemy', 'loot', 'boss'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','F','F','F','F','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },
  {
    id: 'preset_narrow_dead_end',
    name: 'Narrow Dead End',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.7,
    allowRotation: true,
    spawnSlots: [
      { x: 3, y: 1, types: ['enemy', 'loot', 'spawn', 'boss'] },
      { x: 4, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 3, types: ['enemy', 'loot'] },
      { x: 4, y: 3, types: ['enemy', 'loot'] },
      { x: 3, y: 5, types: ['enemy', 'loot', 'boss'] },
      { x: 4, y: 5, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 3,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
      ['W','W','W','F','F','W','W','W'],
    ],
  },
  {
    id: 'preset_room_antechamber',
    name: 'Antechamber',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.5,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 5, y: 1, types: ['enemy', 'loot'] },
      { x: 2, y: 3, types: ['enemy', 'loot'] },
      { x: 5, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 3, y: 5, types: ['enemy', 'loot'] },
      { x: 6, y: 5, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },
  {
    id: 'preset_wide_dead_end',
    name: 'Wide Dead End Room',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.4,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn', 'boss'] },
      { x: 5, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 2, y: 3, types: ['enemy', 'loot'] },
      { x: 5, y: 3, types: ['enemy', 'loot'] },
      { x: 1, y: 5, types: ['enemy', 'loot', 'boss'] },
      { x: 5, y: 5, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','W','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','W','F','W'],
      ['F','F','F','F','F','F','F','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  // ═══════════════════════════════════════════════════════
  // NEW ROOM SHAPES — interior variety & tactical cover
  // Pillars, ring paths, crypt niches, guard posts, gates.
  // ═══════════════════════════════════════════════════════
  {
    id: 'preset_room_pillar',
    name: 'Pillar Room',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.8,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 4, y: 2, types: ['enemy', 'loot', 'boss'] },
      { x: 1, y: 4, types: ['enemy', 'loot'] },
      { x: 6, y: 5, types: ['enemy', 'loot'] },
      { x: 3, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','W','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','W','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },
  {
    id: 'preset_room_ring',
    name: 'Ring Room',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.7,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 1, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
      { x: 2, y: 3, types: ['enemy', 'loot'] },
      { x: 5, y: 4, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: false,
    canBeSpawn: true,
    tiles: [
      ['W','W','F','F','F','F','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','W','W','F','F','W'],
      ['W','F','F','W','W','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },
  {
    id: 'preset_room_crypt_niche',
    name: 'Crypt Niche Room',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.6,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot'] },
      { x: 3, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 4, y: 4, types: ['enemy', 'loot'] },
      { x: 1, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },
  {
    id: 'preset_room_guard_post',
    name: 'Guard Post',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.6,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 3, types: ['enemy', 'loot'] },
      { x: 5, y: 4, types: ['enemy', 'loot', 'boss'] },
      { x: 1, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','F','F','F','F','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },
  {
    id: 'preset_room_gatehouse',
    name: 'Gatehouse',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.7,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 6, y: 1, types: ['enemy', 'loot', 'spawn'] },
      { x: 3, y: 3, types: ['enemy', 'loot', 'boss'] },
      { x: 4, y: 4, types: ['enemy', 'loot'] },
      { x: 1, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy', 'loot'] },
    ],
    maxEnemies: 4,
    maxChests: 2,
    canBeBoss: true,
    canBeSpawn: true,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','F','F','F','F','F','F','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },

  // ═══════════════════════════════════════════════════════
  // CORRIDOR VARIANTS — spatial rhythm & chokepoints
  // Zigzags, collapses, and ambush alcoves add texture
  // to corridor-heavy regions of the dungeon.
  // ═══════════════════════════════════════════════════════
  {
    id: 'preset_corridor_ambush',
    name: 'Ambush Corridor',
    purpose: 'empty',
    contentRole: 'flexible',
    width: 8,
    height: 8,
    weight: 0.8,
    allowRotation: true,
    spawnSlots: [
      { x: 1, y: 6, types: ['enemy'] },
      { x: 3, y: 6, types: ['enemy', 'loot'] },
      { x: 4, y: 6, types: ['enemy', 'loot'] },
      { x: 6, y: 6, types: ['enemy'] },
    ],
    maxEnemies: 3,
    maxChests: 1,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','F','F','F','F','F','F','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },
  {
    id: 'preset_corridor_zigzag',
    name: 'Zigzag Corridor',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.7,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','F','F','F','F','W','W'],
      ['W','W','F','F','F','F','W','W'],
      ['W','W','W','F','F','F','W','W'],
      ['W','W','F','F','F','W','W','W'],
      ['W','W','W','F','F','F','W','W'],
      ['W','W','F','F','F','W','W','W'],
      ['W','W','F','F','F','F','W','W'],
      ['W','W','F','F','F','F','W','W'],
    ],
  },
  {
    id: 'preset_corridor_collapsed',
    name: 'Collapsed Corridor',
    purpose: 'corridor',
    contentRole: 'structural',
    width: 8,
    height: 8,
    weight: 0.7,
    allowRotation: true,
    spawnSlots: [],
    maxEnemies: 0,
    maxChests: 0,
    canBeBoss: false,
    canBeSpawn: false,
    tiles: [
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','W','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['F','F','F','F','F','F','F','F'],
      ['W','W','W','W','W','W','W','W'],
      ['W','W','W','W','W','W','W','W'],
    ],
  },
];

/** Generation size presets */
export const SIZE_PRESETS = [
  { name: 'Tiny',   gridRows: 2, gridCols: 2, label: '2×2 (16×16 tiles)' },
  { name: 'Small',  gridRows: 3, gridCols: 3, label: '3×3 (24×24 tiles)' },
  { name: 'Medium', gridRows: 4, gridCols: 4, label: '4×4 (32×32 tiles)' },
  { name: 'Large',  gridRows: 5, gridCols: 5, label: '5×5 (40×40 tiles)' },
];

export default PRESET_MODULES;
